# Generated by Django 4.2 on 2023-04-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mails',
            fields=[
                ('sno', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=80, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
